Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,36 +1,20 @@
-# This is a basic workflow to help you get started with Actions
+declare -a num1s=()
+declare -a num2s=()
 
-name: CI
+i=1
+while [ $i -lt 11 ]; do
+  num1s+="$(( $RANDOM % 99 + 1 )) "
+  num2s+="$(( $RANDOM % 99 + 1 )) "
+  ((i++))
+done
 
-# Controls when the workflow will run
-on:
-  # Triggers the workflow on push or pull request events but only for the main branch
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
-
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
-jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
-
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
-        run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+for num1 in ${num1s[@]}; do
+  for num2 in ${num2s[@]}; do
+    if [ $(./calc.sh '+' $num1 $num2) -eq $(($num1 + $num2)) ] && [ $(./calc.sh '-' $num1 $num2) -eq $(($num1 - $num2)) ] && [ $(./calc.sh '*' $num1 $num2) -eq $(($num1 * $num2)) ] && [ $(./calc.sh '/' $num1 $num2) -eq $(($num1 / $num2)) ]; then
+      echo "$num1, $num2: test passed"
+    else
+      echo "$num1, $num2: test failed"
+      exit 1
+    fi
+  done
+done
